### ISSUE TITLE
Création des endpoints en lien avec les API d'API-SECU

### ISSUE THREAD

**Issue by ghost** [etalab/siade_staging_data#13]
Bonjour,

Dans le cadre de l'intégration de 2 APIs exposées par API-SECU (API Prestations / CSS et API Famille / Quotient Familial), serait-il possible de créer les 2 répertoires en lien avec les endpoints qui seront exposés par API-Particulier, afin que je puisse y déposer les données Bac à Sable.

Si la procédure n'est pas la bonne, n'hésitez pas à me contacter.

Bien cordialement,
Frédéric Thery-Merland (CNAV)

**Comment by skelz0r** [comment]
Bonjour,

L'API n'étant pas encore disponible sur notre applicatif, le dossier n'existe pas encore dans `payloads/`

Cependant je viens de pousser un nouveau dossier `future_payloads/` avec 2 sous dossiers correspondant aux 2 API, je vous invite à déposer vos fichiers dans ces 2 dossiers dans une nouvelle branche et de faire une pull request, nous itérerons (si besoin) depuis cette PR.

Cordialement.

**Comment by Un3x** [comment]
C'est fait depuis un moment, je close.
